### ISSUE TITLE
Doubt about datum uncertainty

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-calculator#2]
I used the calculator to add the uncertainty for a locality with coordinate taken from GPS but no datum recorded in the data. I filled the next parameters in the calculator and get an uncertainty of 2353 meters. 

![image](https://user-images.githubusercontent.com/15789737/97024461-73bd8580-151c-11eb-9345-389926b3e1d6.png)

I think the value came from a comparison between the geographic coordinates systems in that area and the WGS84 SRS, ¿is that right?. 

My second question is if for some countries is possible to add a default value, for example in Colombia the main Geographic Institute establishes an uncertainty due to coordinates systems used in Colombia of approx 500 m.

**Comment by tucotuco** [comment]
> I used the calculator to add the uncertainty for a locality with coordinate taken from GPS but no datum recorded in the data. I filled the next parameters in the calculator and get an uncertainty of 2353 meters.
> 
> ![image](https://user-images.githubusercontent.com/15789737/97024461-73bd8580-151c-11eb-9345-389926b3e1d6.png)
> 
> I think the value came from a comparison between the geographic coordinates systems in that area and the WGS84 SRS, ¿is that right?.

Yes, that is correct.
 
> My second question is if for some countries is possible to add a default value, for example in Colombia the main Geographic Institute establishes an uncertainty due to coordinates systems used in Colombia of approx 500 m.

You would have to do it a slightly different way. Select WGS84 as a datum in the calculator (which will give no uncertainty from that source) and add 500 m either to the Measurement error or the GPS Accuracy, depending on the coordinates source chosen. We use the maximum difference between any datums to determine the value at the given coordinates because in the age of GPS, anyone could travel to Colombia and use their GPS with the datum set to anything. We can't guarantee that the datum chosen on a GPS is in use in Colombian cartography.
